###
GET https://jsonplaceholder.typicode.com/posts/
Accept: application/json

###
GET http://localhost:3000/api/heroes
Accept: application/json

###
DELETE http://localhost:3000/api/heroes/6457a746-8067-422b-bba7-c6ddb675706e
Accept: application/json

###
POST http://localhost:3000/api/heroes
Content-Type: application/json
Accept: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "knownAs": "JD",
  "house": "Florida"
}

###
PUT http://localhost:3000/api/heroes/058cf4cf-cdb7-4b7f-acc9-ad0f2f9869f6
Content-Type: application/json

{
  "firstName": "John - Updated",
  "lastName": "Doe - Updated",
  "knownAs": "JD - Updated",
  "house": "Florida - Updated"
}

